### ISSUE TITLE
Rofi update makes some themes hard to read.

### ISSUE THREAD

**Issue by MilesStorm** [tinted-theming/base16-rofi#14]
Rofi version 1.7.* makes names of options the wrong color, while using the darker versions of these themes. From what i can tell it makes them all black, so in darker themes this makes options really hard to read. 

When tested on 1.6.1 color displays as intended, while updating to 1.7.1 makes the names of options the wrong color.

**Comment by theova** [comment]
I can confirm this: The same issue on my side...

**Comment by MilesStorm** [comment]
I've locally pulled and built with pull request #13 which fixes the issue. Would recommend maintainer to merge. Would recommend @jordiorlando to merge that pull request.

**Comment by theova** [comment]
Are there any updates?
@YousofMersal : How can I build the themes?

**Comment by jordiorlando** [comment]
@YousofMersal @theova sorry for the delay, I have just merged #13 . Let me know if anything is broken.
