### ISSUE TITLE
Please tag a new release

### ISSUE THREAD

**Issue by FrostyX** [tinted-theming/base16-rofi#15]
Hello @jordiorlando,
can you please tag a new release?

I created a Fedora package for this project.
https://copr.fedorainfracloud.org/coprs/frostyx/rofi-themes-base16/

and I would like to submit the package to the official Fedora repositories. But the problem is that I build it from a commit instead of a tag, and it will raise eyebrows during package review.

**Comment by jordiorlando** [comment]
Closed with v0.1.0

**Comment by FrostyX** [comment]
Thank you :+1:
