### ISSUE TITLE
Needs update for Rofi 1.4.x

### ISSUE THREAD

**Issue by jordiorlando** [tinted-theming/base16-rofi#2]
New theme engine breaks old themes

**Comment by ilpianista** [comment]
I did it, but unfortunately I discovered this repo after [my work](https://github.com/ilpianista/base16-rofi) (this repo isn't listed in [base16's README](https://github.com/chriskempson/base16/blob/master/README.md).

**Comment by jordiorlando** [comment]
Hmm, it was accepted as an official template a while back, but idk if it was ever in the Readme. I'd be happy to accept a PR if you'd like to unify?
