### ISSUE TITLE
Remove or fix rofi.sh hook

### ISSUE THREAD

**Issue by kepi** [tinted-theming/base16-rofi#8]
I'm not sure how this came to light. Please remove `rofi.sh` hook untill better version is available.

Another approach would be to change `echo` line to `Your config file was destroyed (:evilsmiley:), but enjoy new theme.`

I really appreciate there is base16 theme for rofi. But I'm absolutely not OK with software destroying my config file, without asking, because petty color theme change... I have hourly backups but many users don't. And it bad enough to loose last hour of config changes.

Please always think hard, when manipulating with configuration files. In most cases your software isn't only one who is changing it and users can have tons of precious configuration there.

Same wrong approach is currently used in base16-manager. I'm working on PR for it, feel free to take parts from it and adjust it for this hook.

Btw. there is check to existence of config file in hook... So if config file doesn't exist and it would be totally ok to put new config with theme there - it does nothing. But if config file exists, it overwrites it :/ Maybe there should be `!` before config file check? That would be much much better.

**Comment by jordiorlando** [comment]
Sorry, I had no idea! I haven't actually used this hook, I simply accepted the PR. I now realize I should have tested it first. Will add a warning and fix the `!` issue for now, at least until I or someone else has time to fix it properly. Thanks for pointing this out!

**Comment by kepi** [comment]
Thanks, I'm closing issue as from my poin it is solved. If me or somebody else have time to prepare better alternative, we can just create new PR.
